#===============================================================================
# ProjectEuler.Net
# Problem #002: Even Fibonacci Numbers
# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:
#         
#         1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.
#===============================================================================

limit = 4000000
fibSum = 0
f1 = 1
f2 = 1
f1hold = 0

while f2 < limit:
    f1hold = f2
    f2 = f1 +f2
    f1 = f1hold
    if f1 % 2 == 0:
        fibSum = fibSum + f1

print(fibSum)

#===============================================================================
# 4613732
#===============================================================================
