#===============================================================================
# ProjectEuler.Net
# Problem #002: Even Fibonacci Numbers
# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:
#         
#         1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.
#===============================================================================

limit = 4000000
a=c(1,1)
while (a[length(a)] < limit) {
        a[length(a)+1]=a[length(a)]+a[length(a)-1]
}
a = a[1:length(a)-1]
b = a %% 2 == 0
c = a[b]
sum(c)

#[1] 4613732